import collections.abc
import prexsyn_engine.chemspace
import prexsyn_engine.descriptor
import prexsyn_engine.enumerator
import typing

class DataPipeline:
    def __init__(self, chemical_space: prexsyn_engine.chemspace.ChemicalSpace, molecule_descriptors: collections.abc.Mapping[str, prexsyn_engine.descriptor._MoleculeDescriptor], synthesis_descriptors: collections.abc.Mapping[str, prexsyn_engine.descriptor._SynthesisDescriptor], enumerator_config: prexsyn_engine.enumerator.EnumeratorConfig = ...) -> None: ...
    def get(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> dict: ...
    def start_workers(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None: ...
    def stop_workers(self) -> None: ...
